package com.voip.voip_user_mgmt_api.dto;

/**
 * STEP 10: JWT Response DTO
 * 
 * This DTO is returned to the user after successful login.
 * It contains the JWT token and basic user information that the client
 * will use for subsequent authenticated requests.
 * 
 * Authentication Flow Context:
 * 1. User submits login credentials (LoginRequest)
 * 2. AuthController validates credentials and generates JWT token
 * 3. AuthController creates JwtResponse with token and user info
 * 4. JwtResponse is returned to user as JSON
 * 5. User extracts token and includes it in Authorization header for future requests
 * 
 * Response Structure:
 * - token: The JWT token string (required for authentication)
 * - type: Always "Bearer" (standard for JWT tokens)
 * - username: User's username (for client-side display)
 * - name: User's display name (for client-side display)
 * 
 * Security Notes:
 * - Password is NEVER included in this response
 * - Token contains minimal user information (username only)
 * - Token has expiration time for security
 */
public class JwtResponse {
    
    /**
     * JWT token string - This is what the client will use in Authorization header
     * Format: "Bearer <token>"
     * Example: "Bearer eyJhbGciOiJIUzI1NiJ9..."
     */
    private String token;
    
    /**
     * Token type - Always "Bearer" for JWT tokens
     * This follows the OAuth 2.0 Bearer token standard
     */
    private String type = "Bearer";
    
    /**
     * Username - The username used for login
     * Useful for client-side display and logging
     */
    private String username;
    
    /**
     * Display name - User's full name
     * Useful for client-side display (e.g., "Welcome, John Doe")
     */
    private String name;

    /**
     * Default constructor required by Spring for JSON serialization
     */
    public JwtResponse() {
    }

    /**
     * Constructor for creating JWT response after successful authentication
     * 
     * @param token - JWT token generated by JwtUtils
     * @param username - User's username
     * @param name - User's display name
     */
    public JwtResponse(String token, String username, String name) {
        this.token = token;
        this.username = username;
        this.name = name;
    }

    // Getters and setters
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
